spring:
  application:
    name: autoservice-lite-crm
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: INFO